//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CvPROJE
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class DBCVENTITYEntitiess : DbContext
    {
        public DBCVENTITYEntitiess()
            : base("name=DBCVENTITYEntitiess")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<TBLABOUTME> TBLABOUTME { get; set; }
        public virtual DbSet<TBLADDRESS> TBLADDRESS { get; set; }
        public virtual DbSet<TBLCONTACT> TBLCONTACT { get; set; }
        public virtual DbSet<TBLMYWORKS> TBLMYWORKS { get; set; }
        public virtual DbSet<TBLSKİLLS> TBLSKİLLS { get; set; }
        public virtual DbSet<TBLADMIN> TBLADMIN { get; set; }
    }
}
