//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CvPROJE
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBLABOUTME
    {
        public int ID { get; set; }
        public string INFORMATIONS { get; set; }
        public string EDUCATIONS { get; set; }
        public string WORKEXPERIENCES { get; set; }
    }
}
